### ISSUE TITLE
Allow passing parameter handle when overriding a parameter

### ISSUE THREAD

**Issue by AUTProgram** [OxfordIonTrapGroup/ndscan#212]
The `override_param` method of `Fragment` currently accepts an initial value to override default value of the passed parameter and then returns the newly created store underlying the overridden parameter. It would be nice if that method could also accept the handle (or maybe store) of another parameter such that the value of the overridden parameter is forced to be the same as the parameter corresponding to the passed handle.
One use case for this is forcing several parameters from subfragments to have a common value. At the moment, this seems to be only possible by creating a parameter in top-level fragment, calling `override_param` on the relevant params in subfragments, keeping the returned stores as attributes and then manually setting the values of all those stores in `device_setup`. While also making sure that `device_setup` of the subfragments is only called afterwards to have the updated value (for non-overridden parameters, this is usually taken care of automatically by ndscan during a scan, I think). This is a bit roundabout and would be easier if one could just pass the top-level parameter to the `override_param` method and let ndscan take care of the rest.

Or is there currently already an easier way of doing this in ndscan?

**Comment by dnadlinger** [comment]
I don't think there is a way to do this yet, but getting the flexibility for things like this was most of the reason behind the split parameter handle/parameter value design.

**Comment by pmldrmota** [comment]
This would then also allow discovery and execution of the subfragment's default analyses where the axis parameter has been overridden to follow a scanned parameter of the parent as described by @AUTProgram. Currently, the analysis can't be detected sensibly by the filter as it cannot know that those parameters march in lockstep.

**Comment by pmldrmota** [comment]
What about adding a `setattr_params_rebind` method to rebind several parameters to one, such as the following pseudo-implementation? Could probably restrict it to parameters of the same `Fragment` class, to make sure they are compatible in `HandleType` etc.

```python
    def setattr_params_rebind(self,
                              name: str,
                              original_params: List[Tuple["Fragment", Union[str, None]]],
                              **kwargs) -> ParamHandle:

        # Set up our own copy of the parameter.
        # TODO assert all params are compatible or pick one as template (first in list?)
        template_param = original_params[0][0]._free_params[original_params[0][1]]
        param = deepcopy(template_param)
        param.fqn = self.fqn + "." + name
        for k, v in kwargs.items():
            setattr(param, k, v)
        self._free_params[name] = param
        handle = param.HandleType(self, name)
        setattr(self, name, handle)

        assert name not in self._rebound_subfragment_params
        self._rebound_subfragment_params[name] = []
        for original_name, original_owner in original_params:
            # Deregister it from the original owner and make sure we set the store
            # to our own later.
            original_handles = original_owner._get_all_handles_for_param(original_name)
            del original_owner._free_params[original_name]
            self._rebound_subfragment_params[name] += original_handles        

        return handle
```

**Comment by hartytp** [comment]
> This would then also allow discovery and execution of the subfragment's default analyses where the axis parameter has been overridden to follow a scanned parameter of the parent as described by @AUTProgram. Currently, the analysis can't be detected sensibly by the filter as it cannot know that those parameters march in lockstep.

> What about adding a setattr_params_rebind method to rebind several parameters to one, such as the following pseudo-implementation? Could probably restrict it to parameters of the same Fragment class, to make sure they are compatible in HandleType etc.

Does the implementation you sketched out above allow execution of a subfragment's default analysis when the axis parameter has been overridden to follow a scanned parameter? I was curious so sketched something like this out. It falls over inside `match_default_analysis` because it can't match the axis handle in https://github.com/OxfordIonTrapGroup/ndscan/blob/9d46a98df2abafa61640b6d8085a59491b240441/ndscan/experiment/subscan.py#L135

**Comment by hartytp** [comment]
> This would then also allow discovery and execution of the subfragment's default analyses where the axis parameter has been overridden to follow a scanned parameter of the parent as described by @AUTProgram. Currently, the analysis can't be detected sensibly by the filter as it cannot know that those parameters march in lockstep.

I think what you have in mind here something like the following pseudocode

```python
import logging
import ndscan.experiment as nd


logger = logging.getLogger(__name__)


class BaseExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_param("param", nd.FloatParam, "a parameter", 0)
        self.setattr_result("result", nd.FloatChannel)

    def run_once(self):
        self.result.push(0)

    def get_default_analyses(self):
        def _analysis_fun(axis_values, result_values, analysis_results):
            logger.info("base analysis...")
            analysis_results['fit_result'].push(axis_values[self.param][0])

        return [
            nd.OnlineFit("line", data={"x": self.param, "y": self.result}),
            nd.CustomAnalysis(
                [self.param],
                _analysis_fun,
                [nd.FloatChannel("fit_result")]
            )
        ]

class ParentExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_fragment("base", BaseExp)
        self.setattr_param_rebind('param', self.base, description="a parent param")

    def get_default_analyses(self):
        def _analysis_fun(axis_values, result_values, analysis_results):
            logger.info("parent analysis...")
            analysis_results['parent_fit_result'].push(axis_values[self.param][0])

        parent_analysis = nd.CustomAnalysis(
            [self.param],
            _analysis_fun,
            [nd.FloatChannel("parent_fit_result")]
        )
        return self.base.get_default_analyses() + [parent_analysis]

    def run_once(self):
        self.base.run_once()


ScanBaseExp = nd.make_fragment_scan_exp(BaseExp)
ScanParentExp = nd.make_fragment_scan_exp(ParentExp)
```

I had incorrectly convinced myself that the analysis wouldn't be executed for `ParentExp` because it has a different [`ParamHandle`](https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/parameters.py#L141) to `base` (different `fqn`, `description`) despite having the same underlying [`ParamStore`](https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/parameters.py#L30). In fact, of course, ndscan [filters](https://github.com/OxfordIonTrapGroup/ndscan/blob/7dd4a9de5255bf5a92a38750e020d0eaa7b17385/ndscan/experiment/scan_runner.py#L339) analyses based on the store not handles. When the analyses are [executed](https://github.com/OxfordIonTrapGroup/ndscan/blob/9d46a98df2abafa61640b6d8085a59491b240441/ndscan/experiment/default_analysis.py#L228) ndscan maps the handles to the relevant store so each analysis sees a version of `axis_values` that matches their handles. So there is no issue here and everything works as I would have hoped. Working late last night I clearly confused myself.

**Comment by hartytp** [comment]
Right, I see where I was running into trouble...the above works as expected for scans which are executed via a `TopLevelRunner` but it does not work if `ParentExp` is run as part of a subscan. Consider the following (admittedly contrived!) example

```python
import logging
import ndscan.experiment as nd


logger = logging.getLogger(__name__)


class BaseExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_param("param", nd.FloatParam, "a parameter", 0)
        self.setattr_result("result", nd.FloatChannel)

    def run_once(self):
        self.result.push(0)

    def get_default_analyses(self):
        def _analysis_fun(axis_values, result_values, analysis_results):
            logger.info("base analysis...")
            analysis_results['fit_result'].push(axis_values[self.param][0])

        return [
            nd.OnlineFit("line", data={"x": self.param, "y": self.result}),
            nd.CustomAnalysis(
                [self.param],
                _analysis_fun,
                [nd.FloatChannel("fit_result")]
            )
        ]

class ParentExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_fragment("base", BaseExp)
        self.setattr_param_rebind('param', self.base, description="a parent param")

    def get_default_analyses(self):
        def _analysis_fun(axis_values, result_values, analysis_results):
            logger.info("parent analysis...")
            analysis_results['parent_fit_result'].push(axis_values[self.param][0])

        parent_analysis = nd.CustomAnalysis(
            [self.param],
            _analysis_fun,
            [nd.FloatChannel("parent_fit_result")]
        )
        return self.base.get_default_analyses() + [parent_analysis]

    def run_once(self):
        self.base.run_once()

class SubscanExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_fragment('parent', ParentExp)
        nd.setattr_subscan(
            self,
            "scan",
            self.parent,
            [(self.parent, "param")],
            expose_analysis_results=True,
        )

    def run_once(self):
        scan_params = nd.LinearGenerator(-1, 1, 5, True)
        _, _, results = self.scan.run([(self.parent.param, scan_params)])

ScanBaseExp = nd.make_fragment_scan_exp(BaseExp)
ScanParentExp = nd.make_fragment_scan_exp(ParentExp)
ScanScanExp = nd.make_fragment_scan_exp(SubscanExp)
```

Scanning parent exp via the scan exp works as expected. But trying to run the subscan version hits [this](https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/subscan.py#L139) `AssertionError` in the subscan code. AFAICT the issue here is that `subscan` does the look up by handle value rather than comparing the sinks.

If I modify https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/subscan.py#L137 to
```python
        def get_axis_index(handle):
            for i, h in enumerate(coordinate_sinks.keys()):
                if handle._store == h._store:
                    return i
            assert False
```

Everything behaves as expected for the subscan as well. I would generally have expected the check in subscan to be based on stores rather than handles, matching the behavior in `TopLevelRunner`. @dnadlinger is this a bug in subscan that I should submit a PR or have I not understood what is going on here?

**Comment by pmldrmota** [comment]
I think that's a bug and subscans should do the same as the `TopLevelRunner`.

Regarding

> I think what you have in mind here something like the following pseudocode

What I was referring to was 

> One use case for this is forcing several parameters from subfragments to have a common value. At the moment, this seems to be only possible by creating a parameter in top-level fragment, calling override_param on the relevant params in subfragments, keeping the returned stores as attributes and then manually setting the values of all those stores in device_setup. While also making sure that device_setup of the subfragments is only called afterwards [...]

If I slightly modify your example to demonstrate what this describes:
```python
import ndscan.experiment as nd

class BaseExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_param("param", nd.FloatParam, "a parameter", 0)
        self.setattr_result("result", nd.FloatChannel)

    def run_once(self):
        self.result.push(0)

    def get_default_analyses(self):
        def _analysis_fun(axis_values, result_values, analysis_results):
            logger.info("base analysis...")
            analysis_results['fit_result'].push(axis_values[self.param][0])

        return [
            nd.OnlineFit("line", data={"x": self.param, "y": self.result}),
            nd.CustomAnalysis(
                [self.param],
                _analysis_fun,
                [nd.FloatChannel("fit_result")]
            )
        ]

class ParentExp(nd.ExpFragment):
    def build_fragment(self):
        self.base_exps = [self.setattr_fragment(f"base{i}", BaseExp) for i in range(10)]
        self.param_stores = [base_exp.override_param('param')[1] for base_exp in self.base_exps]

        self.setattr_param('param', nd.FloatParam, description="a parent param")

    @kernel
    def device_setup(self):
        for store in self.param_stores:
            store.set_value(self.param.get())
        self.device_setup_subfragments()

    def run_once(self):
        for base_exp in self.base_exps:
            base_exp.run_once()


ScanBaseExp = nd.make_fragment_scan_exp(BaseExp)
ScanParentExp = nd.make_fragment_scan_exp(ParentExp)
```
The `ScanParentExp` would not run the default analyses of the `BaseExp` subfragments because their value has been overridden and is therefore never associated with a scan axis.

The restriction is that `setattr_param_rebind()`, for which you just demonstrated that the default analyses work in a typical scan experiment as expected, currently only rebinds a single parameter. We are looking for an extension to be able to merge multiple parameters together using the same terminology. I believe that https://github.com/OxfordIonTrapGroup/ndscan/issues/212#issuecomment-910319625 would do the job, but I don't know if we want to have two rebind methods with different signatures, ie
```python
def setattr_param_rebind(self,
                         name: str,
                         original_owner: "Fragment",
                         original_name: Union[str, None] = None,
                         **kwargs) -> ParamHandle
```
with the known call pattern and
```python
def setattr_params_rebind(self,
                          name: str,
                          original_params: List[Tuple["Fragment", Union[str, None]]],
                          **kwargs) -> ParamHandle
```
with the call pattern
```python
self.setattr_params_rebind('param', [(self.base_exp_0, 'param'), (self.base_exp_1, 'param')])
```
or extend the call signature of the existing `setattr_param_rebind()` method to something like
```python
def setattr_param_rebind(self,
                         name: str,
                         original_owner: Union["Fragment", List["Fragment"]],
                         original_name: Union[str, List[str], None]]],
                         **kwargs) -> ParamHandle
```
with the different supported call patterns
```python
self.setattr_param_rebind('param', self.base_exp)
self.setattr_param_rebind('parent', self.base_exp, 'param')
self.setattr_param_rebind('param', [self.base_exp_0, self.base_exp_1])
self.setattr_param_rebind('parent', [self.base_exp_0, self.base_exp_1], 'param')
self.setattr_param_rebind('parent', [self.base_exp_0, self.base_exp_1], ['param', 'param'])
```

To be honest, I don't like this proliferation. Instead, I can imaging changing the `setattr_param_rebind()` signature to
```python
def setattr_param_rebind(self,
                         name: str,
                         original_params: List[ParamHandle],
                         **kwargs) -> ParamHandle
```
by passing handles rather than (fragment instance, parameter name), since the handles carry that information anyway in `handle.owner` and `handle.name`. The rebind signature would be a lot more transparent.
Existing parent code would change to `self.setattr_param_rebind(['param', self.base_exp.param])` and the above example would look like
```python
class ParentExp(nd.ExpFragment):
    def build_fragment(self):
        self.base_exps = [self.setattr_fragment(f"base{i}", BaseExp) for i in range(10)]
        self.setattr_param_rebind('param', [base_exp.param for base_exp in self.base_exps])

    def run_once(self):
        for base_exp in self.base_exps:
            base_exp.run_once()
```
and (in my mental model) correctly execute all default analyses.

**Comment by hartytp** [comment]
> and (in my mental model) correctly execute all default analyses.

Am I right in thinking that in the example you posted no default analyses will be executed since [`ExpFragment.get_default_analyses`](
https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/fragment.py#L610) returns an empty list by default, rather than iterating over child fragments?

So strictly, the parent fragment needs to implement `get_default_analyses` which concatenates and returns the child fragment analyses? However, because the child fragment analysis results all have the same name, the parent also needs to rename those results to avoid collisions. So, the implementation ends up looking something like the following (rough, untested) pseudocode:

```
def get_default_analyses():
    def wrap_analysis_fn(analysis_fun, axis_values, wrapped_result_values, analysis_results):
        result_values = {}
        for wrapped_path, channel in result_values.items():
            original_path = wrapped_path[:wrapped_path.rfind('_')]  # not tested, but you get what I'm after here...
            result_values[original_path] = channel
        return analysis_fun(axis_values, result_values, analysis_results)

    analyses = []
    for exp_id, exp in enumerate(self.self.base_exps):
        for analysis in exp.get_default_analyses():
            if not isinstance(analysis, nd.CustomAnalysis):
                analyses.append(analysis)
                continue
            anslysis._result_channels = {f"{k}_{exp_id}": v for k, v in anslysis._result_channels.items()}

            analysis._analyze_fn = lambda *args: wrap_analysis_fn(analysis._analyze_fn, *args)
```

Without this wrapping, I think your experiment hits [this](https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/default_analysis.py#L202) exception but please do correct me if I'm wrong here.

I'm not sure if this is a common enough situation that it's worth supporting it in a nicer way? This is what I had in mind when I posted https://github.com/OxfordIonTrapGroup/ndscan/issues/278

**Comment by hartytp** [comment]
```python
        # TODO assert all params are compatible or pick one as template (first in list?)
        template_param = original_params[0][0]._free_params[original_params[0][1]]
```

How do we want to handle this? AFAICT asserting that all parameters are compatible is not a good option -- e.g. consider the case where the parameter descriptions are different. Picking the first one in the list feels liable to generate surprises. I don't love it but how about making this more explicit:

```python
def setattr_param_rebind(self,
                         name: str,
                         original_param: ParamHandle,
                         extra_params: Optional[List[ParamHandle]]=None,
                         **kwargs) -> ParamHandle
```

**Comment by pmldrmota** [comment]
> Am I right in thinking that in the example you posted no default analyses will be executed since [ExpFragment.get_default_analyses](https://github.com/OxfordIonTrapGroup/ndscan/blob/408dc02aad102be550776f8bc39551bc0e46f4b6/ndscan/experiment/fragment.py#L610) returns an empty list by default, rather than iterating over child fragments?

Ah of course, yes.

> How do we want to handle this? AFAICT asserting that all parameters are compatible is not a good option -- e.g. consider the case where the parameter descriptions are different. Picking the first one in the list feels liable to generate surprises.

But what about parameter types, for example rebinding a mixture of `FloatParam`, `IntParam`, perhaps even `StringParam`? Do we want to allow that? If both are numeric types, maybe that's fine, but can likewise generate surprises.

**Comment by hartytp** [comment]
After 2dfdda7d1d40c4e9dc04de17d0fd6d31f016b07d the following experiment
```python
import logging
import ndscan.experiment as nd


logger = logging.getLogger(__name__)


class BaseExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_param("param", nd.FloatParam, "a parameter", 0)
        self.setattr_param("int_param", nd.IntParam, "an integer parameter", 0)
        self.setattr_result("result", nd.FloatChannel)

    def run_once(self):
        self.result.push(0)

    def get_default_analyses(self):
        def _analysis_fun(axis_values, result_values, analysis_results):
            logger.info(f"{'_'.join(self._fragment_path)} analysis...")
            analysis_results['fit_result'].push(axis_values[self.param][0])

        return [
            nd.OnlineFit("line", data={"x": self.param, "y": self.result}),
            nd.CustomAnalysis(
                [self.param],
                _analysis_fun,
                [nd.FloatChannel("fit_result")]
            )
        ]

class ParentExp(nd.ExpFragment):
    def build_fragment(self):
        self.base_exps = [self.setattr_fragment(f"base{i}", BaseExp) for i in range(3)]
        self.setattr_param_rebind(
            'param',
            self.base_exps[0].param,
            ([exp.param for exp in self.base_exps[1:]] +
             [exp.int_param for exp in self.base_exps]
            ),
            description="a parent param"
        )

    def run_once(self):
        for base_exp in self.base_exps:
            base_exp.run_once()


class SubscanExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_fragment('parent', ParentExp)
        nd.setattr_subscan(
            self,
            "scan",
            self.parent,
            [(self.parent, "param")],
            expose_analysis_results=True,
        )

    def run_once(self):
        scan_params = nd.LinearGenerator(-1, 1, 5, True)
        _, _, results = self.scan.run([(self.parent.param, scan_params)])

ScanBaseExp = nd.make_fragment_scan_exp(BaseExp)
ScanParentExp = nd.make_fragment_scan_exp(ParentExp)
ScanScanExp = nd.make_fragment_scan_exp(SubscanExp)
```

Now gives `AssertionError: Field 'int_param' of type <class 'ndscan.experiment.parameters.IntParamHandle'> does not match type of original parameter ('<class 'ndscan.experiment.parameters.FloatParamHandle'>'`

**Comment by dnadlinger** [comment]
The discussion here has evolved away quite a bit from the original issue title, but as we are all here anyway and will hopefully wrap up this discussion in the next couple days anyway, I'll just respond here.

Comparing the handles rather than the stores in the analysis matcher wasn't as much a bug as a conservative design decision, as I couldn't really think of a clear use case where you would want the other behaviour. You seem to have run into this in practice and found it untuitive, which is pretty much all I need to be convinced to change it, but I'm still curious as to what the scenario actually was.

Same goes for the composition of default analyses. As they are "execution hints" for a particular top-level ExpFragment, I didn't originally envision them being collected across the fragment tree. Speaking of which, there is only a `Fragment` tree precisely for this reason, the `ExpFragment` character of any such fragment used as a subfragment is lost. What is your use case here? Bundling multiple ExpFragments together into a single one so that they share a single kernel invocation?

I think I'd prefer making the "forwarding" of the results in the sub-`ExpFragment` use case explicit, just as you already need to manually specify what running that composite fragment means (by calling the child fragment `run_once()`s in a loop). In fact, while I'm still happy with the choice of collecting all the parameters across the fragment tree – the express purpose of which is to allow the user to "reach under the hood" in a fashion similar to dependency injection –, I've come to think of `ResultChannel`s auto-aggregating in the same fashion as a bit of a design blunder, as they are qualitatively different and just aggregating them limits the flexibility (cf. the discussion on "absorbing" results elsewhere).

If you find yourself needing this often, I suppose you could add a `CollectionExpFragment` or something that encapsulates this pattern. Results with the same name, but from different analyses, probably indeed collide, which is checked in https://github.com/OxfordIonTrapGroup/ndscan/blob/4806105486dd737ac1cd5e6c1dc4af6e86488b8f/ndscan/experiment/subscan.py#L271.
If we implement some disambiguation in the execution logic, the `ParentExp.get_default_analyses()` implementation from your example (or otherwise some generic `CollectionExpFragment` version) would simply be case of concatenating the results from the `BaseExp`s, which might be a nice simplification. But again, as default analyses were never intended to be aggregated across the fragment tree, there is no path context available to the subscan runner at that point which would allow using that for generating the disambiguated names/descriptions/… instead of something inscrutable like sequential identifiers.

Thking this over, I think I would indeed prefer implementing this in a composable fashion in something like a `CollectionExpFragment` (`AggregateExpFragment`? `OmnibusExpFragment`?), which we could add into upstream ndscan, as it does seem to be occasionally useful (I recall writing this out manually for taking long-running time-series scans of several fragments at some point). The way to implement the analysis result disambiguation cleanly would be to create a DefaultAnalysis subclass that proxies another DefaultAnalysis, passing through everything, but injecting the extra path (provided by `CollectionExpFragment`) into the names, and possibly also the descriptions.

**Comment by hartytp** [comment]
> You seem to have run into this in practice and found it untuitive, which is pretty much all I need to be convinced to change it, but I'm still curious as to what the scenario actually was.

Here is an example: I have a generic `ExpFragment` for quadrupole laser (time, detuning, etc) scans. It has analyses to find transition frequencies from detuning scans, etc. I now want to write a really basic experiment which determines the magnetic field by scanning across a pair of transitions. A convenient means of doing this is to create a second `ExpFragment` called `TwoTransitions729`  or whatever which (in rough pseudocode) looks like:

```python
class Two729Transitions(nd.ExpFragment):
    def build_fragment(self, t0, t1):
        self.setattr_device("core")
        self.setattr_fragment("t0", fragments.quadrupole.Simple729Carrier, t0)
        self.setattr_fragment("t1", fragments.quadrupole.Simple729Carrier, t1)
        self.setattr_param_rebind("detuning", t0, [t1], description="Detuning from transitions")
        self.t0.readout.p.description = f"{self.t0} bright population"
        self.t1.readout.p.description = f"{self.t1} bright population"
        self.t0.readout.p.display_hints["share_axis_with"] = self.t1.readout.p.path

    @kernel
    def run_once(self):
        self.t0.run_once()
        self.t1.run_once()
```

With #282 and #283 I can rebind the detuning parameters of both child `ExpFragments` and get result values out. Obviously there are other ways of doing this but it seems like a valid use case that allows us to abstract over the details of how the scan is done rather than duplicate it.

**Comment by hartytp** [comment]
Anyway, it broadly sounds like your feeling is that https://github.com/OxfordIonTrapGroup/ndscan/pull/283 is not a feature you want to merge so I'll close that now. I don't think I have a strong enough sense of what a good design would look like for the kind of collection experiment you described to do any work in that direction at the moment, so I think I'll leave this here for now (it's not an issue I've hit often so it's fine if the solution is a bit ad hoc).

**Comment by hartytp** [comment]
okay. I'm still not sure I fully understand what the solution you have in mind looks like so I sketched out a quick [strawman](https://github.com/OxIonics/upstream-ndscan/tree/collection_exp) so we can discuss something concrete.

This implements a collection experiment, analysis proxy and result binding. Is this the kind of thing you had in mind?
